### ISSUE TITLE
PEP8 code styling

### ISSUE THREAD

**Issue by tony** [qencode-dev/qencode-api-python-client#7]
It's typical for python projects to adhere to [PEP8](https://www.python.org/dev/peps/pep-0008/). I'm wondering if there's any opinions/thoughts on it?

Generally that entails [4 space indents](https://www.python.org/dev/peps/pep-0008/#indentation).

Most open source python projects follow the same general styling conventions.

While this may be a bikeshed in other programming languages, historically Python squared its styling issues away early on.

Any thoughts on this? If so, any preferred way of doing it?

**Comment by sdil** [comment]
We can use black formatter to format the whole repo.

**Comment by tony** [comment]
@sdil If that is the case, you can merge #1 (which runs black on the codebase)

Or you can make your own PR to add black and merge the changes, as well, of course

If / when the codebase formatting is merged to master, let me know, I will rebase #6 against the changes. The code changes should be easier to see after that.

For qencode-python3 (though technically that project would be obsolete as #6 gets this project to handle python 2 and 3): https://github.com/qencode-dev/qencode-api-python3-client/pull/5
